### ISSUE TITLE
Use after free in G8Tesseract.mm

### ISSUE THREAD

**Issue by mdenty** [gali8/Tesseract-OCR-iOS#129]
The **- (UIImage *)thresholdedImage** message crashes always because of an use after free.
The code is:
```
- (UIImage *)thresholdedImage
{
    Pix *pixs = _tesseract->GetThresholdedImage();
    Pix *pix = pixUnpackBinary(pixs, 32, 0);

    pixDestroy(&pixs);

    return [self imageFromPix:pix];
}
```
It should be:
```
- (UIImage *)thresholdedImage
{
    Pix *pixs = _tesseract->GetThresholdedImage();
    Pix *pix = pixUnpackBinary(pixs, 32, 0);

    UIImage* img = [self imageFromPix:pix];
    pixDestroy(&pixs);

    return img;
}
```
After editing the *thresholdedImage* message, it does not crash anymore but the grabbed image is solid black...

**Comment by kevincon** [comment]
Interesting, well the method seems to work fine in our tests. Can you provide us with the general steps you're taking and their order when you call `thresholdedImage`? Like calling an init method, setting image, anything else?

**Comment by mdenty** [comment]
Context: I've created a wrapper swift class to replace my old implementation of Tesseract wrapper with yours.
The wrapper is a singleton that may be called multiple times for the same image.
I've add the Clear method to your wrapper since I have a memory leak of the internal pix image if I do not call Clear() between two images.
tesseract let value is initialized once in the singleton constructor
```
    private let tesseract:G8Tesseract
    private override init() {
        if let documentPath = applicationDocumentsDirectory() {
            // Set up the tessdata path. This is included in the application bundle
            // but is copied to the Documents directory on the first run.
            // tessdata copy code removed for readability
            tesseract = G8Tesseract(language: "fra+eng6", configDictionary: nil, configFileNames: nil, cachesRelatedDataPath: documentPath, engineMode: G8OCREngineMode.TesseractOnly)
        } else {
            tesseract = G8Tesseract(language: "fra+eng6")
        }
        super.init()
        tesseract.delegate = self
    }




```
 
Here are the methods of interest:
```
    func useImage(image:UIImage) {
        tesseract.image = image.g8_blackAndWhite()
    }
    
    func recognizeInRect(rect:CGRect) -> String {
        tesseract.rect = rect
        return recognize()
    }
    
    func recognize() -> String {
        if tesseract.recognize() {
            return tesseract.recognizedText
        }
        return ""
    }
    
    func freeCurrentImage() {
        tesseract.clear()
    }
    
    // MARK: G8TesseractDelegate
    func shouldCancelImageRecognitionForTesseract(tesseract: G8Tesseract!) -> Bool {
        return false
    }
```

For testing purposes, I've modified the recognized method like this:
```
    func recognize() -> String {
        if tesseract.recognize() {
            UIImageWriteToSavedPhotosAlbum(tesseract.thresholdedImage, nil, nil, nil)
            return tesseract.recognizedText
        }
        return ""
    }
```

So, when I called this version of recognize() the application crashed at each run (note that I call the recognizeInRect() method most of the time).
As stated in the code of leptonica you are using a pointer after 

Let me know if

**Comment by kevincon** [comment]
Just as a sanity check (I'm sure you are), but you're calling your `useImage` method before `recognize`, right? What happens if you don't apply `g8_blackAndWhite()` to the image before giving it to Tesseract? Do you still get the crash?

### Now to analyze the code:

Our `thresholdedImage` method calls `Pix *pixs = _tesseract->GetThresholdedImage();`, which creates a copy of the internal thresholded image from Tesseract, and the caller must pixDestroy it:

```
/**
   * Get a copy of the internal thresholded image from Tesseract.
   * Caller takes ownership of the Pix and must pixDestroy it.
   * May be called any time after SetImage, or after TesseractRect.
   */
  Pix* GetThresholdedImage();
```
Source: https://code.google.com/p/tesseract-ocr/source/browse/api/baseapi.h?name=3.03-rc1#378

Next, we call `Pix *pix = pixUnpackBinary(pixs, 32, 0);`, which returns `pixd`, where `pixd` is the result of calling one of the `pixConvert1ToX` where X can be one of [2, 4, 8, 16].

Now, [in each of those calls to `pixConvert1ToX`](https://tpgit.github.io/Leptonica/pixconv_8c_source.html#l01387), the first argument is `NULL`, for example: `pixd = pixConvert1To2(NULL, pixs, 0, 3);`. [According to the documentation for each of the `pixConvert1ToX` functions](https://tpgit.github.io/Leptonica/leptprotos_8h.html#a5b3cf59edc39c9b75011ac60932f105a), setting the first argument to `NULL` will cause the function to return a brand new pix (via `pixCreate`, which [ensures "data allocated and initialized to 0"](https://tpgit.github.io/Leptonica/leptprotos_8h.html#a009df4671d39f94b50a0368af210aebe)).

Therefore `pix` in `Pix *pix = pixUnpackBinary(pixs, 32, 0);` should be a brand new pix with separate data from `Pix *pixs = _tesseract->GetThresholdedImage();`, right? Which I believe would mean it is okay to call `pixDestroy(&pixs);` before calling `[self imageFromPix:pix]`.

### Further analysis of `imageFromPix`

Now here's a possibility with why `imageFromPix` is crashing. First, here's `imageFromPix`:

``` Objective-C
- (UIImage *)imageFromPix:(Pix *)pix
{
    // Get Pix parameters
    l_uint32 width = pixGetWidth(pix);
    l_uint32 height = pixGetHeight(pix);
    l_uint32 bitsPerPixel = pixGetDepth(pix);
    l_uint32 bytesPerRow = pixGetWpl(pix) * 4;
    l_uint32 bitsPerComponent = 8;
    // By default Leptonica uses 3 spp (RGB)
    if (pixSetSpp(pix, 4) == 0) {
        bitsPerComponent = bitsPerPixel / pixGetSpp(pix);
    }

    l_uint32 *pixData = pixGetData(pix);

    // Create CGImage
    CGDataProviderRef provider = CGDataProviderCreateWithData(NULL, pixData, bytesPerRow * height, NULL);
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();

    CGImageRef cgImage = CGImageCreate(width, height,
                                       bitsPerComponent, bitsPerPixel, bytesPerRow,
                                       colorSpace, kCGBitmapByteOrderDefault,
                                       provider, NULL, NO, kCGRenderingIntentDefault);

    CGDataProviderRelease(provider);
    CGColorSpaceRelease(colorSpace);
    pixDestroy(&pix);

    // Draw CGImage to create UIImage
    //      Creating UIImage by [UIImage imageWithCGImage:] worked wrong
    //      and image became broken after some releases.
    CGRect frame = { CGPointZero, CGSizeMake(width, height) };
    UIGraphicsBeginImageContextWithOptions(frame.size, YES, self.image.scale);
    CGContextRef context = UIGraphicsGetCurrentContext();

    // Context must be mirrored vertical
    CGContextTranslateCTM(context, 0, height);
    CGContextScaleCTM(context, 1.0, -1.0);
    CGContextDrawImage(context, frame, cgImage);

    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();

    UIGraphicsEndImageContext();
    CGImageRelease(cgImage);

    return image;
}
```

Notice that we're calling `pixDestroy(&pix);` before we call `CGContextDrawImage(context, frame, cgImage);`, which is where you said you are experiencing the crash.

`CGContextDrawImage` uses `cgImage`, which we create using:

```
CGImageRef cgImage = CGImageCreate(width, height,
                                       bitsPerComponent, bitsPerPixel, bytesPerRow,
                                       colorSpace, kCGBitmapByteOrderDefault,
                                       provider, NULL, NO, kCGRenderingIntentDefault);
```

And `CGImageCreate` uses `provider`, which is created using `CGDataProviderRef provider = CGDataProviderCreateWithData(NULL, pixData, bytesPerRow * height, NULL);`.

[According to the documentation for `CGDataProviderCreateWithData`](https://developer.apple.com/library/ios/documentation/GraphicsImaging/Reference/CGDataProvider/index.html#//apple_ref/c/func/CGDataProviderCreateWithData), `provider` gives access to the `pixData` pointer whenever the provider is used.

Finally, `CGImageCreate` uses `provider` to create `cgImage`. [According to the documentation for `CGImageCreate`](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGImage/index.html#//apple_ref/c/func/CGImageCreate), "Quartz retains [the provider]; on return, you may safely release it." Which would suggest it's okay to release the `provider`, as we do. 

### Hotfix

But it's not clear that it's okay to call `pixDestroy(&pix);` before calling `CGContextDrawImage(context, frame, cgImage);`. So I have created a hotfix branch on my fork to try delaying the `pixDestroy(&pix);` call until after `CGContextDrawImage(context, frame, cgImage);`.

Can you try it out and see if it fixes the issue for you? If you're using CocoaPods, you can use this line in your Podfile to try it out:

```
pod 'TesseractOCRiOS', :git => 'https://github.com/kevincon/Tesseract-OCR-iOS.git', :branch => 'hotfix-imagefrompix'
```

@BamX, since you wrote `imageFromPix`, do you agree with my analysis and hotfix?

*Footnote: The Leptonica documentation links above are for 1.68 (we use 1.71 in this library), but I don't believe the functions have changed semantically from version to version.*

**Comment by BamX** [comment]
Absolutely! That's my bad, sorry. I think this hotfix will solve this issue.

**Comment by ws233** [comment]
Will this fix a totally black thresholded image?
I also have it accessing this property.

**Comment by kevincon** [comment]
I haven't tried it to see if it does; can you try it and let us know? Also @mdenty did you get a chance to try the hotfix yet?

**Comment by mdenty** [comment]
Not tested yet, sorry. I'm too busy for now.

**Comment by ws233** [comment]
I did move the pixDestroy to the end and it seems it fixed totally black thresholded image issue.
But it seems that it's inverted. Perhaps, that what is necessary for further upstream tesseract processing. So I think that should be mentioned in the .h.

So, do we need to check all other pixDestroy in our code?

**Comment by ws233** [comment]
And what's wrong with tests? Why do they work?

**Comment by kevincon** [comment]
I think our test right now is quite limited; doesn't it only perform the thresholding on the 0123456789 image?

Also, maybe it's an issue that only becomes apparent in Swift for some reason...

**Comment by mdenty** [comment]
The hotfix seems to do its job. It just works here.

**Comment by ws233** [comment]
> Also, maybe it's an issue that only becomes apparent in Swift for some reason...
I don't write in swift.
In my case I don't have a crach, but have a totally black image.

**Comment by kevincon** [comment]
I was referring to @mdenty since he's using swift, but I'm glad the hot fix worked for both of you. I'll create a pull request for it tonight or tomorrow, I'm traveling on a plane for most of today.
