### ISSUE TITLE
TessesractOCR.framework is missing

### ISSUE THREAD

**Issue by AasmaRaza** [gali8/Tesseract-OCR-iOS#143]
I have downloaded/cloned the project. Tried manual installation and cocoapods, but there is no framework how will i proceed?

**Comment by kevincon** [comment]
@AasmaRaza can you provide a detailed list of steps you took so that we can try to reproduce your issue? Provide the contents of your project's Podfile, and please also mention your OSX version, Xcode version, and the version of the Tesseract library that you are trying to install (either the latest CocoaPod, 3.4.0, or the development version from this GitHub repo).

**Comment by AasmaRaza** [comment]
Well, I tried both the cocoapods  and GitHub repo. This is the exact error I am getting TesseractOCR/TesseractOCR.h' file not found. Although .h file is present but the framework is missing. I can not find it anywhere in the project file as well. Here are the contents of my own Podfile

![screen shot 2015-02-11 at 8 04 28 am](https://cloud.githubusercontent.com/assets/10925558/6141271/d17ff156-b1c4-11e4-97e9-6b99747b8890.png)

I am using OSX Yosemite 10.10.2 and Xcode 6.1.1. I also tried using the manual installation but still no framework present.

**Comment by kevincon** [comment]
Can you describe the process you used to install the CocoaPod? Can you also post a screenshot of your Xcode window showing the error (particularly the part that shows the files in the project)?

**Comment by AasmaRaza** [comment]
I followed the instructions given here http://cocoapods.org/ to install cocoapods. 
Here is the screen shot of the Xcode window. 
![screen shot 2015-02-11 at 10 24 01 am](https://cloud.githubusercontent.com/assets/10925558/6142435/36330c06-b1d8-11e4-9b59-8942b610174b.png)

**Comment by kevincon** [comment]
I'm confused by the screenshot, since that's showing Template Framework Project and your Podfile mentions a project called "ScratchCard".

One thing that might be tripping you up if you're new to CocoaPods is that, after running `pod install` in the terminal, you need to always open the .xcworkspace file that CocoaPods creates instead of the usual .xcodeproj file. Are you sure you're using the workspace file after installing the CocoaPod?

**Comment by AasmaRaza** [comment]
Actually the problem is that I can not compile the actual TesseractOCR project because there is no framework.

Yes, the Podfile that I sent was of my own project. After creating the Podfile and editing it as mentioned on the installation page cocoa pods won't update, saying that the git repository was not found. There was no . xcworkspace file created as well. May be its because update did not happen. I am new to cocoapods that's why I wanted to try with the manual installation.

**Comment by kevincon** [comment]
Can you post the exact error CocoaPods is giving you about the git repository not being found? I have a feeling that the error is unrelated to this project and might be an issue with your CocoaPods installation because CocoaPods pulls the specs for any pod you want to install from a master git repo.

I'm focusing on helping you with the CocoaPods method of installation because no one else has reported this kind of issue with that method, and honestly the manual installation method is trickier to debug over GitHub because there are several more things that could go wrong.

**Comment by AasmaRaza** [comment]
@kevincon I must say you are a life saver. I just tried updating again so that I could send you the error and the miracle happened. It is ACTUALLY updating pods. Will update you in a while when and if its done. 
![screen shot 2015-02-11 at 11 05 37 am](https://cloud.githubusercontent.com/assets/10925558/6142729/f098a952-b1dd-11e4-8b19-673cde058fe4.png)

**Comment by AasmaRaza** [comment]
Thanks @kevincon it worked. I still don't know why it is working and why it didn't work last night. Appreciate your help. 

I am closing this issue here. Thanks again.
