### ISSUE TITLE
cocoapods tessdata missing

### ISSUE THREAD

**Issue by Abderezai** [gali8/Tesseract-OCR-iOS#145]
Tried the cocoapods route and expected it to work out of the box,
complains that the tessdata is missing. Couldn't find a solid solution.
Attempted the manual install, and the framework was missing.
WT-Ph?

**Comment by kevincon** [comment]
Tessdata files aren't provided in the framework or in the CocoaPod. These are just the standard Tesseract files that you can download from the upstream website at: https://code.google.com/p/tesseract-ocr/downloads/list

For example, for the English language you would download "tesseract-ocr-3.02.eng.tar.gz". Note that within that archive is a "tessdata" folder; this is the folder that you need to import into your Xcode project AS A REFERENCED FOLDER. You'll know if you imported it correctly as a referenced folder because the folder icon will be blue instead of yellow, as shown in this picture:

![image](https://cloud.githubusercontent.com/assets/817753/6143709/e45a6420-b181-11e4-87e1-1f2fc143eca4.png)

One additional note - this library is not really meant to be a "works out of the box for lots of use cases" OCR solution yet. Instead, it's a wrapper for the Tesseract desktop library, compiled for iOS, and as such assumes a little knowledge about the upstream Tesseract library. Granted we could get to a one-stop-shop iOS OCR library one day, but you might consider other solutions like the ABBYY OCR mobile SDK (http://www.abbyy.com/mobileocr/) or a cloud-based solution (http://ocrsdk.com/) if you're looking for a more immediate "out of the box" solution.

**Comment by kevincon** [comment]
I've updated the installation instructions in the Wiki (https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation) to make this more clear, so I'll close this issue. Feel free to reopen it (or create a new issue) if you have any other questions.

**Comment by Abderezai** [comment]
Hi,
I put the blue tessdata folder in my main project, but got the same error:
"Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory."

Where do I copy the folder? how do I set TESSDATA_PREFIX?

Thanks

**Comment by kevincon** [comment]
Can you post the code you're trying to run that is producing the error? Also can you post a screenshot of your project structure, including all sub-files/directories of the tessdata folder?

**Comment by DJLectr0** [comment]
I have the same problem. It is complaining about not finding the eng.tessdata file although I want to use the deu one. Code:
var tesseract:Tesseract = Tesseract();
                                tesseract.language = "deu";
                                tesseract.delegate = self;
                                tesseract.setVariableValue("01234567890", forKey: "tessedit_char_whitelist");
                                tesseract.image = theImage;
                                tesseract.recognize();
                                
                                NSLog("%@", tesseract.recognizedText);

Error:

Error opening data file /private/var/mobile/Containers/Bundle/Application/5059E3B1-E9C3-4169-B2A6-BD734686A6EA/OCR_TEST.app/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
fatal error: unexpectedly found nil while unwrapping an Optional value

Folder structure is the same as you need to

**Comment by kevincon** [comment]
That's strange, would you mind emailing me your OCR_TEST project/workspace folder as a zip file so I can take a closer look? You can email it to me at: kcon AT stanford DOT edu

**Comment by DJLectr0** [comment]
Ok I have sent you the files. Note: I have added some stuff for using a camera picture but the same error occured while using the swift example.

**Comment by kevincon** [comment]
Thanks @DJLectr0, I think I was able to fix it by changing your code to:

``` Objective-C
var tesseract:Tesseract = Tesseract(language: "deu")
tesseract.delegate = self;
tesseract.setVariableValue("01234567890", forKey: "tessedit_char_whitelist");
tesseract.image = theImage;
tesseract.recognize();

NSLog("%@", tesseract.recognizedText);
```

Let me know if that fixes it for you.

If you look in our code, our initializer for Tesseract will use "nil" for the language unless you specify it using the convenience initializer. It looks like if Tesseract receives "nil" for the language, it uses english as a default! Unfortunately I don't think this is something we can really fix with our library because it is a behavior of the upstream Tesseract library, but we can certainly improve the documentation so this is clearer to users. Thanks for catching this!

**Comment by DJLectr0** [comment]
Ok thank you for fixing that it works now.

**Comment by nitishKuMa** [comment]
HI
I got this error,Please help me to resolve it.

Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'chi_sim'
Tesseract couldn't load any languages!

**Comment by shamsher400** [comment]
Create reference not CreateGroup its work for me

**Comment by dinesh45** [comment]
Than you so much!  it's working for me. (Create reference not CreateGroup its work for me).

**Comment by WeiWenTaoApple** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
