### ISSUE TITLE
I can't build this project.

### ISSUE THREAD

**Issue by gracegyu** [gali8/Tesseract-OCR-iOS#146]
I'm using Xcode6.1.1 , OSX 10.9.5

When I build any project include Tesseract OCR iOS.xcodeproj with XCode, "TesseractOCR/TesseractOCR.h file not found" error occurs. 

I followed this guide Option 1 (https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation)

I think there is not TesseractOCR.framework in my directory.
What can I do for it?

**Comment by kevincon** [comment]
First of all, the Wiki is outdated if you're using CocoaPods with version 3.4.0. I recommend you use the development version so you can follow the rest of the instructions in the Wiki.

Have you used CocoaPods before? What's in your Podfile? Did you run `pod install` in terminal to install this library's pod? Was an .xcworkspace file created? Did you open that file to try building your project?

**Comment by gracegyu** [comment]
I haver CocoaPods v0.35.0.

My Podfile is like below
------------------------------------------
source 'https://github.com/CocoaPods/Specs.git'
workspace 'Tesseract-OCR-iOS'
xcodeproj 'TestsProject/TestsProject.xcodeproj/', 'Coverage' => :debug

target 'TestsProjectTests' do

        pod 'Kiwi', '~> 2.3.1'

end

pod 'TesseractOCRiOS', :head
---------------------------------------------------

I have run "pod update" and "pod install". I don't know well about CocoaPods.

I have Tesseract-OCR-iOS.xcworkspace file. Maybe is was created?
There are 3 projects. What should I build? Or steps?

- TestsProject
- Tesseract OCR iOS
- Pods

Thanks.

**Comment by kevincon** [comment]
I see, so you are trying to use the actual code in this repo. All you should have to do for that is build the Template Framework Project target in Tesseract-OCR-iOS.xcworkspace to be able to run the demo application. Does that work for you?

**Comment by gracegyu** [comment]
Is TestsProject demo application?

When I build Tesseract-OCR-iOS.xcworkspace, Errors occurred like below.
```
TestsProjectTests Group
(null): Linker command failed with exit code 1 (use -v to see invocation)
(null): error: unable to open executable '/Users/gracegyu/Library/Developer/Xcode/DerivedData/Tesseract-OCR-iOS-baqmajdbynljmhebctqkgoflpgpc/Build/Products/Debug-iphoneos/TestsProjectTests.xctest/TestsProjectTests'
TestsProject Group
(null): "___gcov_flush", referenced from:
(null): Linker command failed with exit code 1 (use -v to see invocation)
(null): error: unable to open executable '/Users/gracegyu/Library/Developer/Xcode/DerivedData/Tesseract-OCR-iOS-baqmajdbynljmhebctqkgoflpgpc/Build/Products/Debug-iphoneos/TestsProject.app/TestsProject'
```

**Comment by kevincon** [comment]
No, the demo application is actually called "Template Framework Project". It exists as a target in Tesseract-OCR-iOS.xcworkspace, see here, it's checked:

![screen shot 2015-02-11 at 12 55 12 am](https://cloud.githubusercontent.com/assets/817753/6144155/aee770f6-b188-11e4-8869-dac917b0ae99.png)

**Comment by gracegyu** [comment]
Build succeeded.

Thank you very much. 

What is the TestProject?

**Comment by kevincon** [comment]
It contains unit tests for the Tesseract iOS library. You can run the unit tests by setting the target to be the TestsProject and going to the Product menu -> Test. But it will only work if you run `pod install` from the terminal to install the Kiwi unit testing library (that's what the Podfile in this repo is for).

Since this issue is resolved, I'll close it here. Feel free to reopen it (or a new issue) if you have any other problems.

**Comment by gracegyu** [comment]
I'm trying to recognize Sudoku puzzle from newspaper or books with this project.
But there is grid with numbers and blank cell. 
Can you recommend good solution or techknowledge that I can use with Tesseract to recognize sudoku puzzle?

Thanks.

**Comment by kevincon** [comment]
Unfortunately that's difficult to do JUST using Tesseract because Tesseract only performs OCR on black text on a white background and doesn't work very well with irregular text patterns.

It looks like your idea has been done before, and here's an explanation of how one user used OpenCV, potentially in combination with an OCR engine like Tesseract, to achieve his results: http://sudokugrab.blogspot.com/2009/07/how-does-it-all-work.html

Here's another project that seems to only use OpenCV, and it's open-source: https://github.com/Haoest/SudokuResolv

**Comment by gracegyu** [comment]
Thank you. 
I'll try it.
