### ISSUE TITLE
Swift crash at setting image

### ISSUE THREAD

**Issue by DJLectr0** [gali8/Tesseract-OCR-iOS#147]
Hello,

When I want to set my Image for the tesseract object it crashes. Code:
```swift
var tesseract:Tesseract = Tesseract(language: "deu")
tesseract.delegate = self;
tesseract.setVariableValue("01234567890", forKey: "tessedit_char_whitelist");
tesseract.image = theImage;
tesseract.recognize();

NSLog("%@", tesseract.recognizedText);
```
Error:
EXC_BAD_ACCESS
BSXPCMessage received error for message: Connection interrupted

I think that is because in the Obj-C samples you call g8_blackAndWhite on the images. The problem is this function is not available for swift.

**Comment by DJLectr0** [comment]
Hmm I found blackAndWhite, but that still does not work.

**Comment by kevincon** [comment]
I don't believe that's the issue, because you can set `tesseract.image` to be any image, not just one that has been adjusted via `g8_blackAndWhite`.

If this code is from the same OCR_TEST project you sent me before, does that mean the image you are trying to set is something you've captured from the camera? What happens if you add a test image to your app and try using it instead of an image captured from the camera?

**Comment by DJLectr0** [comment]
Its using the camera photo but it just started working.

**Comment by DJLectr0** [comment]
Ok when I do not use the blackAndWhite image it crashes with the error above.

**Comment by DJLectr0** [comment]
grayscale works too, and the test images do not crash when not using grayscale or blackAndWhite

**Comment by DJLectr0** [comment]
When I use a saturation filter and bring down the saturation to 0 it does not need grayscale or blackAndWhite. Maybe It crashes when there are colors?

**Comment by kevincon** [comment]
Tesseract performs best (and really expects) images that are crisp black text on a pure white background (see this article from our Wiki: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-for-Improving-OCR-Results).

But I don't think it should crash on an image that has colors like that. In order for me to best help you debug this issue, can you save an image that causes Tesseract to crash and share it with me? Otherwise I won't be able to reproduce your issue to debug it.

**Comment by DJLectr0** [comment]
![img](https://cloud.githubusercontent.com/assets/5339762/6236643/960c83e6-b6ec-11e4-91b5-08399d158d7b.png)

If I dont use the saturation filter, grayScale or blackAndWhite it crashes

**Comment by kevincon** [comment]
I used the OCR_TEST project you emailed me as a starting point to try to reproduce this issue.

I modified the `viewDidLoad` function in ViewController.swift to be:

``` Swift
override func viewDidLoad() {
        super.viewDidLoad()
        
        let theImage = UIImage(named: "test.png")
        println("Image = \(theImage)")
        var tesseract:Tesseract = Tesseract(language: "deu");
        tesseract.delegate = self;
        tesseract.setVariableValue("01234567890", forKey: "tessedit_char_whitelist");
        tesseract.image = theImage;
        tesseract.recognize();
        
        let recognizedText = tesseract.recognizedText
        
        println("Recognized: \(recognizedText)")
    }
```

I also imported the image you attached above as "test.png".

When I run the app in the iPhone 6 simulator, it does not crash, and the following is printed to the console:

```
Image = Optional(<UIImage: 0x7fcbd0e2bd30>)
Recognized:   
```

So it seems like no text is being recognized (understandable since it's not a very good image for Tesseract to be able to recognize easily), but at least it doesn't crash.

Can you try reproducing what I just described here and see if it works for you? If it does work for you, can you double check your code, maybe set some break points, and see exactly where your app is crashing? Maybe it's not related to Tesseract exactly. The error you quoted (EXC_BAD_ACCESS) is usually related to improper memory management, so maybe it's an issue with how you're passing the image data to Tesseract from the camera?

**Comment by ws233** [comment]
@DJLectr0, I think you should better take a look on here:
https://github.com/gali8/Tesseract-OCR-iOS/issues/130
I think, the reason of a crach is in the wrong imageOrientation.
Pls, confirm, that you didn't rotate image changing UIImage imageOrientation property. Instead for now you should do it by redrawing an image pixel by pixel. We are working on the same code nowadays, but it still is not ready. Refer to the link above for more details.

**Comment by DJLectr0** [comment]
@ws233 You were right, there was not set an orientation for the image. Thank you

**Comment by chenshipeng** [comment]
i also crashed,at [tesseract recognize];with EXC_BAD_ACCESS
