### ISSUE TITLE
Crash when using own language file

### ISSUE THREAD

**Issue by Jaykob** [gali8/Tesseract-OCR-iOS#152]
When using a language file that I trained the test app crashes when calling recognize() with an `EXC_BAD_ACCESS`.
It crashes in the `SquishedDawg::edge_char_of()` function.
The same language file works on my desktop (Mac) test program...
Any ideas what can go wrong here?

Thanks for this great project! :-)

**Comment by kevincon** [comment]
I'm not sure why it's crashing for you with a custom language file. I've also trained a custom language file and it works fine with this library. Are you using the same image to test on both iOS and your desktop? What version of Tesseract are you using on the desktop? It might be worth checking that it matches the version we're using in this iOS library (version 3.03 release candidate 1) and that your custom language file was trained for this version.

If the above ideas don't turn up a reason for the crash, would you be willing to email me your custom language file so I can try to reproduce the crash? You can email it to me at kcon AT stanord DOT edu.

**Comment by kevincon** [comment]
For reference, @Jaykob emailed me his trained data file and a sample image.

I copied lotto.traineddata to my /usr/local/share/tessdata folder and then ran `tesseract -l lotto lotto.jpg stdout` (where lotto.jpg is the image he sent me and lotto.traineddata is the language file he sent me). The result is: 

`[1]    57507 segmentation fault  tesseract -l lotto lotto.jpg stdout`

Here's the output of running `tesseract -v` on my desktop:
```
tesseract 3.03
 leptonica-1.71
  libjpeg 8d : libpng 1.6.13 : libtiff 4.0.3 : zlib 1.2.5 : libopenjp2 2.1.0
```

I'm running the same versions of tesseract and leptonica that are used in this iOS library. Since both my desktop version and the iOS version crash, my thinking is that there might be an issue with the custom language file. Particularly, maybe you created it using an older version of tesseract that is incompatible with version 3.03?

**Comment by Jaykob** [comment]
Sorry for not writing back here.
I tested it on my Mac with the compiled googlecode trunk version from yesterday and it works fine...
Following is the output of `tesseract -v`:
```
    tesseract 3.04.00
    leptonica-1.71
      libgif 4.2.3 : libjpeg 9a : libpng 1.6.16 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.2 : libopenjp2 2.1.0
```

Could you maybe give me a script or some hints on how to compile the trunk version into an iOS framework? Then I could test if I could compile my current version and see if it works. I tried training the language file with the current version but it didn't make any difference. Originally I trained it with 3.02 or 3.03

**Comment by kevincon** [comment]
Oh I see, I hadn't considered that the trunk version would actually be their development for version 3.04. I think that would explain the incompatibility; maybe version 3.04 has some changes that break backwards-compatibility for trained language files.

Since the trunk looks like it's their development branch, I wouldn't try to build it for an iOS framework yet since it's probably unstable. But if you want to try that, everything you need is in this repo under the TesseractOCR folder in the root of the repository. Read the instructions here, taking care to use the trunk version of tesseract instead of the 3.03-rc1 version linked: https://github.com/gali8/Tesseract-OCR-iOS/blob/master/TesseractOCR/README_howto_compile_libaries.md You'll also need to change the `TESSERACT_LIB ` variable in the script, https://github.com/gali8/Tesseract-OCR-iOS/blob/master/TesseractOCR%2Fbuild_dependencies.sh, accordingly to match the name of the tesseract source folder you use. Also note that I don't think we have a "TesseractOCRAggregate" target anymore (step 4 in the instructions), but I think once you complete step 3 you can just try the Template Framework Project example app in the workspace project and see if it works.

I'm not sure which version you mean when you say "I tried training the language file with the current version but it didn't make any difference", but it's actually really easy to install version 3.03-rc1 on Mac if you have homebrew installed (http://brew.sh/). And that's the version this library uses, so at least you'll know they match.Try:

```
brew update
brew install tesseract --devel
```

(note that you might first have to uninstall your version 3.4.0 with homebrew if you used homebrew to install it)

That should install version 3.03-rc1, which is what I have installed on my computer. I used this version to create a custom language file that works with this iOS library, so hopefully it will work for you as well if you re-create your language file after installing version 3.03-rc1.

If that doesn't work, you could also (possibly again if you already have) try using version 3.02 to train your language file, which would just involve removing the `--devel` flag in the homebrew command above.

**Comment by Jaykob** [comment]
Brilliant! Got it working thanks to your great guide and build script :-)
Seems to me like a bug in 3.03-rc1 which they fixed in the meantime.
Thanks again for your help and the great work!
