### ISSUE TITLE
TesseractOC/TesseractOCR.h not found 

### ISSUE THREAD

**Issue by carlosalban** [gali8/Tesseract-OCR-iOS#159]
This is for my own existing project, the template works fine.

#import <TesseractOC/TesseractOCR.h>
Gives me the error: "'TesseractOC/TesseractOCR.h' file not found."

TesseractOCRiOS (3.4.0)
COCOAPODS: 0.36.1

I followed up the podfile instructions and see the following in terminal after I pod install/update:

Pre-downloading: `TesseractOCRiOS` from `https://github.com/gali8/Tesseract-OCR-iOS.git`
Downloading dependencies
Installing TesseractOCRiOS 3.4.0 (was 3.4.0)
Generating Pods project
Integrating client project

Opening workspace.

**Comment by gali8** [comment]
Look at #141

**Comment by kevincon** [comment]
@gali8 I don't think that's the issue here.

@carlosalban I wonder if you've just made a typo in importing the header. It's supposed to be:

```
#import <TesseractOCR/TesseractOCR.h>
```

In particular, notice that there is an "R" in the folder "TesseractOCR". In your import code you put "TesseractOC", without the "R".

Does that resolve the missing import for you?

**Comment by carlosalban** [comment]
Wow. Well that's why you don't program at 3AM. Thanks!
