### ISSUE TITLE
Build script doesn't support building leptonica with zlib, libpng, jpeg, giflib, and libtiff support

### ISSUE THREAD

**Issue by ws233** [gali8/Tesseract-OCR-iOS#173]
In order to implement #172 feature, I would like to rebuild leptonica with all image format support.
I do install autoconf, automake, m4.
I also unpacked leptonica to 'leptonica-1.71' subfolder and tesseract to 'tesseract-3.03' subfolder of a 'TesseractOCR' folder.
Than I run './build_dependencies.sh' from 'TesseractOCR' folder.
During build I receive 'configure: error: leptonica library missing' messages and no libtesseract_all.a output in the build folder at the end.

**Comment by ws233** [comment]
Ah! That was my fault! As I've already mentioned I try to build leptonic with image format support, so I did remove the following flags from the --without-zlib --without-libpng --without-jpeg --without-giflib --without-libtiff build script. Without those flags build fails.
@kevincon, do you know how to add those dependent libraries to the build?

**Comment by kevincon** [comment]
Check out http://www.leptonica.com/source/README.html, the section marked "I/O libraries leptonica is dependent on". It lists the packages you need (at least what they're called on apt-get). Try installing them with homebrew and then editing either the build_dependencies.sh script or the Leptonica Makefile templates directly so you can specify the location of the dependency library files and the dependency header files.

I have a feeling that it might not work, though, because the library files for zlib, libpng, etc. you install using homebrew are built for x86, and thus trying to use them in cross-compiling leptonica for iOS probably won't work. In that case, you'd have to modify the build_dependencies.sh script to compile each of those libraries from source for the target platforms (arm7v, arm64, etc.) and then use the cross-compiled versions of zlib, libpng, etc. when cross-compiling leptonica. Does that make sense? I'm not sure it's worth trying to do just to add PDF output support for #172.

**Comment by ws233** [comment]
Yup. That's quiet difficult. Perhaps, I should search for a different way.

**Comment by ws233** [comment]
Finally, I've succeed with the zlib without all the rest libraries.

**Comment by ws233** [comment]
@kevincon, I've found this https://github.com/ashtons/libtiff-ios.
Those scripts are able to compile libpng, libjpg and libtiff for 5 architectures.
Only the issue, which I have is how to link them with leptonica.
Can you help me with this and modify the build script so it can link with all of those libraries?
I need them for the #172 feature, while generating PDF output.
Thx in advance!

**Comment by ws233** [comment]
I've succeeded with this and with PDF output. I'll upload it soon.

**Comment by ws233** [comment]
Pls, refer to #186.
