### ISSUE TITLE
Can you use alternative languages from Tesseract?

### ISSUE THREAD

**Issue by losh11** [gali8/Tesseract-OCR-iOS#193]
I had read here before that using custom training files for other languages fails.
Not too sure.

**Comment by kevincon** [comment]
Although there have been several reports from users that using custom language files doesn't work, I think generally it's because either they trained the file with a mismatched version of Tesseract from this repo (this repo uses Tesseract 3.03-rc1) or they're trying to use a different engine like cube that is known not to work with user-created language files.

I have been successful in creating a custom language file and using it with this library, so let us know if you have an issue with your own custom language file and we'll help you out.

**Comment by dawanjiali** [comment]
Hello Kevin,

Is the trained data files generated for 3.02 work for this version of Tesseract? I tried Arabic and Turkish files for 3.02 downloaded from Google code and they do not work! Any help would be appreciated

Dawan

**Comment by kevincon** [comment]
@dawanjiali Can you open a separate issue for your question and provide the specific error message you're getting? Also double-check that your trained data files work with Tesseract 3.03-rc1 on your desktop. If it doesn't work with that version on desktop, it won't work with this library either.
