### ISSUE TITLE
building from source doesn't work

### ISSUE THREAD

**Issue by eugeniobaglieri** [gali8/Tesseract-OCR-iOS#243]
Building framework from source doesn't work anymore, i followed successfully the procedure until it says to open the TesseractOCR.xcodeproj and build the "TesseractOCRAggregate" but in the project there is not target called in this way. Instead there is a TesseractOCR.framework and this is not an aggregate framework, in the project also miss a script that build aggregate framework. Maybe needs an update to documentation?

**Comment by ws233** [comment]
No need, since you are reffering a documention for the latest release, but use the developer branch.
Pls, refer `README_howto_compile_libaries.md` and `Makefile` from the sources.
I'm closing the issue.
Feel free to reopen it, if the proposed doesn't help you.

**Comment by eugeniobaglieri** [comment]
i followed also that procedure, i obtain all compiled libraries but not any framework, suggestions?

**Comment by ws233** [comment]
There is no need in "TesseractOCRAggregate" target anymore, since it did the same as Makefile does.
If you need a framework, pls, check all the available targets. There is a `TesseractOCR`. It will create a framework from those .a files you've made with Makefile, as I remember.
Also, "TesseractOCRAggregate" exists in 4.0.0 release as I remeber. If not, sorry.
