### ISSUE TITLE
Tesseract couldn't load any languages!

### ISSUE THREAD

**Issue by Podiya** [gali8/Tesseract-OCR-iOS#250]
Error opening data file /var/mobile/Containers/Bundle/Application/1508F07C-65ED-460E-9BA2-EF0E69BAF806/CC.app/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by huangc10** [comment]
Hi, I'm new to Tesseract but from my understanding, you need to copy over the Language files to the tessdata directory first before any language files can be loaded. 

Please see the answer here on SO: http://stackoverflow.com/questions/21299571/tesseract-running-error-on-xcode

Language files can be obtained here: https://github.com/tesseract-ocr/langdata

I hope this helps.

**Comment by huangc10** [comment]
Sorry please ignore my comment before.

Everything will work as long as you follow the instructions here exactly:
http://cocoadocs.org/docsets/TesseractOCRiOS/4.0.0/docs/guides/Installation.html

It's a bit misleading because from first glance, it seems the information after "Using the Development Version" is relavant to only people using the development version...

However, upon closer inspection you need to follow all the steps starting from: "Import the Libz.dylib to the library"

Note, libz.dylib is now called libz.tbd

**Comment by ws233** [comment]
@Podiya, both comment are correct. You have to follow `Importing the tessdata folder` to import language files corectly. The tessdata folder icon should be BLUE in your project folders tree and be located in the root of your app bundle.
I'm closing the issue as duplicate.
You're free to reopen it if you have any questions, but first pls search the repository for the same issues openned before.

**Comment by Podiya** [comment]
sorry for the delay. yeah i import that folder to my project. that was fix my issue. Thank you very much for u two guys @huangc10 @ws233 :+1:

**Comment by Pikamander2** [comment]
To those getting here from Google, try restarting your PC after adding TESSDATA_PREFIX to your system variables.

I'm running Windows 10 and that's what fixed this error for me.

**Comment by horseshoe7** [comment]
Everything works as expected for english and french.  When I add deu.traineddata and try to initialize tesseract in german, it fails.
