### ISSUE TITLE
Running Tesseract-OCR-iOS without CocoaPods

### ISSUE THREAD

**Issue by Darkoon** [gali8/Tesseract-OCR-iOS#332]
Hey!
I have problems with running Tesseract-OCR-iOS using CocoaPods in my hybrid mobile application. Is there any chance to use tesseract without pods, using some kind of static libs or something like that?

**Comment by Rufy86** [comment]
https://www.raywenderlich.com/93276/implementing-tesseract-ocr-ios

Follow this tutorial.

However in the zip you download there is a version in which you compile a framework to import

**Comment by kevinmlong** [comment]
@gali8 @kevincon - couldn't you add the built framework into your releases so that carthage users could easily incorporate it? I was able to clone the repo and build framework (had to set ENABLE_BITCODE to NO) and copy it into my project and it seems to work. 

Having a framework binary in the release would be a huge help though!
