### ISSUE TITLE
Can't Build Project for Release

### ISSUE THREAD

**Issue by hirad** [gali8/Tesseract-OCR-iOS#46]
I have an app using Tesseract which runs just fine in development, but when I want to archive it, I get a series of warnings:

```
warning: no rule to process file '...../Pods/TesseractOCRiOS/TesseractOCR/lib/liblept.a' of type archive.ar for architecture armv7
warning: no rule to process file '...../Pods/TesseractOCRiOS/TesseractOCR/lib/libtesseract_all.a' of type archive.ar for architecture armv7
warning: no rule to process file '...../Pods/TesseractOCRiOS/TesseractOCR/lib/liblept.a' of type archive.ar for architecture armv7s
warning: no rule to process file '...../Pods/TesseractOCRiOS/TesseractOCR/lib/libtesseract_all.a' of type archive.ar for architecture armv7s
warning: no rule to process file '...../Pods/TesseractOCRiOS/TesseractOCR/lib/liblept.a' of type archive.ar for architecture arm64
warning: no rule to process file '...../Pods/TesseractOCRiOS/TesseractOCR/lib/libtesseract_all.a' of type archive.ar for architecture arm64
```

And, of course, archiving fails due to `undefined symbols for architecture`. 

Any tips on this?

I've read this can be caused by having the wrong files in "Compile Sources", but as far as I can tell, I only have .m files and core data models in there.

**Comment by pwansch** [comment]
Hi Kevin,
I just created a brand new iOS 8.1 project in Xcode 6.1.1, added this line to a blank Podfile:
pod 'TesseractOCRiOS', '3.4.0'
and nothing else and did pod install. When I open my project Snap.xcworkspace, I see the following:

![snap](https://cloud.githubusercontent.com/assets/1839855/5811121/3c34669c-a006-11e4-9ad2-bc9567289258.png)

The framework files in the Pods project are red, because they refer to /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/System/Library/Frameworks/Foundation.framework 
which does not exist since I only have iOS8.1 installed.
How can I make it work so that I can get to try the awesome sample?

Thank you!

**Comment by ws233** [comment]
Hi, @pwansch.
Could you try this #111 and tell us if it helps?

**Comment by kevincon** [comment]
@pwansch, I created a new project using the same steps as you did, and although I also see those items in red like you do, building and running the project works perfectly fine (see screenshot below).

The only red items that refer to the iOS7.1-related path are Foundation.framework and UIKit.framework in Pods/Frameworks/iOS. This seems to be an issue with CocoaPods itself, but I can assure you that everything will still build correctly regardless. Here's the related issue on CocoaPods: CocoaPods/CocoaPods#2324

Screenshot of the 3.4.0 Cocoapod running fine using the same version of Xcode as you:

![screen shot 2015-01-20 at 11 48 10 am](https://cloud.githubusercontent.com/assets/817753/5824823/af8a6480-a09b-11e4-891c-f674e93d8d84.png)

**Comment by pwansch** [comment]
Thank you @kevincon. This perfectly answered my question.
