### ISSUE TITLE
The TesseractOCR/TesseractOCR.h can't found when add TesseractOCR.framework to existing project

### ISSUE THREAD

**Issue by lbwxly** [gali8/Tesseract-OCR-iOS#70]
I following the instruction to add the framework to my existing project, but get following error:
"TesseractOCR/TesseractOCR.h file not found"

**Comment by nitinumaretiya123** [comment]
i have installed pod 'TesseractOCRiOS', '3.1.1' but cant able to  "import TesseractOCR" @kevincon @lbwxly

**Comment by kevincon** [comment]
@nitinumaretiya123 the latest version is 4.0.0, not 3.1.1. See the installation instructions at https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation. 

If you're still having trouble after following those instructions, please create a new issue instead of commenting on an old issue like this one.
