### ISSUE TITLE
Achieve 100% testing coverage

### ISSUE THREAD

**Issue by zachberger** [gali8/Tesseract-OCR-iOS#85]
It would be good to get some unit testing up and running for the framework. Although the framework is written in Objective-C its possible to test via Swift. Testing in Swift might be a gentle way to transition into a Swift-only future (speculating).  

Would anyone be opposed to that, or would we like to keep everything in Objective-C?

**Comment by ws233** [comment]
Unit testing fails on iOS7.1 Simulator.

**Comment by BamX** [comment]
Fixed here: #121

**Comment by kevincon** [comment]
It'd be great to measure our test coverage. Here's a guide on how to do that: http://qualitycoding.org/xcode-code-coverage/ if someone wants to take a look. Then we could add a badge to the README that (hopefully) says "Coverage: 100%".

**Comment by ws233** [comment]
By the way, we use Travis CI for the tests.
Does it have this functanality? It should, I guess.

**Comment by kevincon** [comment]
I'm not sure Travis CI does natively, but it supports some other services that do. Maybe we can use this: https://coveralls.io/ It would require @gali8 to sign up with his Github login since he owns the repository, but it's free for open-source projects and CocoaPods actually uses it for their testing coverage.

**Comment by kevincon** [comment]
@gali8 just another bump to activate this repo on https://coveralls.io/ so we can add a test coverage percentage badge to the README.

**Comment by gali8** [comment]
The repo is linked to coveralls and the badge is already in the readme. 
Look at your email @kevincon. I send you the repo token etc...

**Comment by kevincon** [comment]
Thanks so much @gali8! We now have coveralls working with the repo. :)

Notice we only have 79% coverage with our tests; we should aim to improve that if we can. Here you can see the coverage by file for the most recent commit:
https://coveralls.io/builds/1721123

**Comment by ws233** [comment]
Thank you a lot from my side as well, @gali8!

That's a good value! Greate progress! :)
Perhaps, we should create subtasks for remaining uncoverred lines and spread them between us.
But let's do this after the grand release :)

**Comment by ws233** [comment]
I've uploaded a PR #135 with unit tests for G8RecognizedBlock.
They help to find a bug in isEqual and hash function.
First, was here:

       else if ([super isEqual:other] == NO) {
            return NO;
       }

As apple documentation says: "The default NSObject implementation of isEqual: simply checks for pointer equality." (https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaEncyclopedia/Introspection/Introspection.html).

That actually means, that the code ebove produces the following behavour:

      G8RecohnizedBlock *block1 = [[G8RecohnizedBlock alloc] init];
      G8RecohnizedBlock *block2 = [[G8RecohnizedBlock alloc] init];
      [block1 isEqual:block2] == NO;   // That's definitely wrong!

That's why I've changed the isEqual method and replaced super isEqual call with comparing self.hash method. Again, as Apple doc says two equal methods should have equal hashes.

Also I've checked the hash method to satisfy the condition above and found out that hash doesn't consider bounding box. That's not a big issue, but it's better to have it included into the hash function.
@BamX, can you add it to hash?

**Comment by BamX** [comment]
How should we calculate hash of 4 CGFloat values? I've thought about it and not found any good solution for it.

**Comment by ws233** [comment]
what if we use NSStringFromCGRect and use its hash instead?

**Comment by ws233** [comment]
There is another affort: https://gist.github.com/steipete/6133152

**Comment by BamX** [comment]
It's very accurate. If the same block will be with any little change in accuracy of bounding box it will broke everything. We could use rounded values like (NSInteger)(height*1000) and 1000 will be a constant. What are you think?

**Comment by ws233** [comment]
Do we need this rounding by the way?
In such case the comparison in the isEqual method should also be changed to consider this rounding.
I mean, can we use the same rounding, which is used here:

        result = result && CGRectEqualToRect(self.boundingBox, otherBlock.boundingBox);

Anybody nows how this function does rounding?

**Comment by BamX** [comment]
We don't have to make hash use all information of block. This approximation will be good, I think. But I don't know, how ```CGRectEqualToRect``` actually works.

**Comment by ws233** [comment]
We don't, that's right. But it's better to include as many info there as possible, since the comparing first done according to the hash value and it's much faster than comparing the whole object property by property.
Anyway, if you decide not to include it in hash, I'm ok with it.

And I'm also going to insert return NO after every property comparing. I think it will work much faster, if the code doesn't need to check all the properties after one is already failed.

What do you think about it?

**Comment by BamX** [comment]
Sure. And I think bounding box should be added to hash with small accuracy.

**Comment by ws233** [comment]
ok. can you add it?

**Comment by BamX** [comment]
I'm a little busy now. Could you write CGRect hash method yourself and add to #135 ?

**Comment by ws233** [comment]
ok. I'll take this.

**Comment by ws233** [comment]
#169 is the last commit I could propose for test coverage.
Does anybody knows how to cover those @try @catch blocks all over the code?

**Comment by kevincon** [comment]
I'm not sure about how to hit them, but it might be possible to exclude those lines if we were able to use lcov instead of gcov: http://stackoverflow.com/questions/3555083/how-do-i-tell-gcov-to-ignore-un-hittable-lines-of-c-code

This looks like a promising project that we could try, and it uses lcov behind-the-scenes and hooks into Coveralls nicely: https://github.com/venmo/slather I'm pretty swamped at work but feel free to give it a shot if you have time, and let me know if you need me or @gali8 to setup anything for the repo.
